import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id:1,
    firstName: "Adarsh",
    lastName: "Balika",
    username: "adarshbalika@gmail.com",
    password: "adarshBalika123",
    userHandler:"adarshbalika24",
    bookmarks:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Jennifer",
    lastName: "Lawrence",
    username: "jenniferlawrence",
    password: "jenniferLawrence123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Leonardo",
    lastName: "DiCaprio",
    username: "leonardodicaprio",
    password: "leonardoDiCaprio123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Angelina",
    lastName: "Jolie",
    username: "angelinajolie",
    password: "angelinaJolie123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Tom",
    lastName: "Cruise",
    username: "tomcruise",
    password: "tomCruise123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Brad",
    lastName: "Pitt",
    username: "bradpitt",
    password: "bradPitt123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Emma",
    lastName: "Watson",
    username: "emmawatson",
    password: "emmaWatson123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Robert",
    lastName: "Downey Jr.",
    username: "robertdowneyjr",
    password: "robertDowneyJr123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Scarlett",
    lastName: "Johansson",
    username: "scarlettjohansson",
    password: "scarlettJohansson123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Chris",
    lastName: "Evans",
    username: "chrisevans",
    password: "chrisEvans123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Dwayne",
    lastName: "Johnson",
    username: "dwaynejohnson",
    password: "dwayneJohnson123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Natalie",
    lastName: "Portman",
    username: "natalieportman",
    password: "nataliePortman123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Johnny",
    lastName: "Depp",
    username: "johnnydepp",
    password: "johnnyDepp123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },
    {
    _id: uuid(),
    firstName: "Meryl",
    lastName: "Streep",
    username: "merylstreep",
    password: "merylStreep123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    },{
      _id: uuid(),
      firstName: "Amitabh",
      lastName: "Bachchan",
      username: "amitabhbachchan",
      password: "amitabhBachchan123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Shah Rukh",
      lastName: "Khan",
      username: "shahrukhkhan",
      password: "shahRukhKhan123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Aishwarya",
      lastName: "Rai",
      username: "aishwaryarai",
      password: "aishwaryaRai123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Priyanka",
      lastName: "Chopra",
      username: "priyankachopra",
      password: "priyankaChopra123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Salman",
      lastName: "Khan",
      username: "salmanKhan",
      password: "salmanKhan123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Deepika",
      lastName: "Padukone",
      username: "deepikapadukone",
      password: "deepikaPadukone123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Ranveer",
      lastName: "Singh",
      username: "ranveersingh",
      password: "ranveerSingh123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Kareena",
      lastName: "Kapoor",
      username: "kareenakapoor",
      password: "kareenaKapoor123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Hrithik",
      lastName: "Roshan",
      username: "hrithikroshan",
      password: "hrithikRoshan123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      },
      {
      _id: uuid(),
      firstName: "Alia",
      lastName: "Bhatt",
      username: "aliabhatt",
      password: "aliaBhatt123",
      createdAt: formatDate(),
      updatedAt: formatDate(),
      }
];
