import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: 1,
    firstName: "Adarsh",
    lastName: "Balika",
    username: "adarshbalika@gmail.com",
    password: "adarshBalika123",
    userHandler: "adarshbalika24",
    profilePic:"https://www.giantbomb.com/a/uploads/scale_small/0/6087/2437349-pikachu.png",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  
  {
    _id: uuid(),
    firstName: "Jennifer",
    lastName: "Lawrence",
    username: "jenniferlawrence@gmail.com",
    password: "jenniferLawrence123",
    userHandler: "jenniferLawrence123",
    profilePic:"https://d26oc3sg82pgk3.cloudfront.net/files/media/edit/image/47148/article_aligned%402x.jpg",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Leonardo",
    lastName: "DiCaprio",
    username: "leonardodicaprio@gmail.com",
    password: "leonardoDiCaprio123",
    userHandler: "leonardoDiCaprio123",
    profilePic:"https://www.pngmart.com/files/22/Charizard-Pokemon-Download-PNG-Image.png",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Angelina",
    lastName: "Jolie",
    username: "angelinajolie@gmail.com",
    password: "angelinaJolie123",
    userHandler: "angelinaJolie123",
    profilePic:"https://www.pngmart.com/files/22/Charizard-Pokemon-Download-PNG-Image.png",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Tom",
    lastName: "Cruise",
    username: "tomcruise@gmail.com",
    profilePic:"https://www.pngmart.com/files/22/Charizard-Pokemon-Download-PNG-Image.png",
    password: "tomCruise123",
    userHandler: "tomCruise123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Brad",
    lastName: "Pitt",
    username: "bradpitt@gmail.com",
    password: "bradPitt123",
    profilePic:"https://www.pngmart.com/files/22/Charizard-Pokemon-Download-PNG-Image.png",
    userHandler: "bradPitt123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Emma",
    lastName: "Watson",
    username: "emmawatson@gmail.com",
    password: "emmaWatson123",
    userHandler: "emmaWatson123",
    bookmarks: [],
    profilePic:"https://www.pngmart.com/files/22/Charizard-Pokemon-Download-PNG-Image.png",
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Robert",
    lastName: "Downey Jr.",
    username: "robertdowneyjr@gmail.com",
    password: "robertDowneyJr123",
    userHandler: "robertDowneyJr123",
    bookmarks: [],
    followers:[],
    profilePic:"https://www.pngmart.com/files/22/Charizard-Pokemon-Download-PNG-Image.png",
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Scarlett",
    lastName: "Johansson",
    username: "scarlettjohansson@gmail.com",
    password: "scarlettJohansson123",
    userHandler: "scarlettJohansson123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Chris",
    lastName: "Evans",
    username: "chrisevans@gmail.com",
    password: "chrisEvans123",
    userHandler: "chrisEvans123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Dwayne",
    lastName: "Johnson",
    username: "dwaynejohnson@gmail.com",
    password: "dwayneJohnson123",
    userHandler: "dwayneJohnson123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Natalie",
    lastName: "Portman",
    username: "natalieportman@gmail.com",
    password: "nataliePortman123",
    userHandler: "nataliePortman123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Johnny",
    lastName: "Depp",
    username: "johnnydepp@gmail.com",
    password: "johnnyDepp123",
    userHandler: "johnnyDepp123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Meryl",
    lastName: "Streep",
    username: "merylstreep@gmail.com",
    password: "merylStreep123",
    userHandler: "merylStreep123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Amitabh",
    lastName: "Bachchan",
    username: "amitabhbachchan@gmail.com",
    password: "amitabhBachchan123",
    userHandler: "amitabhBachchan123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Shah Rukh",
    lastName: "Khan",
    username: "shahrukhkhan@gmail.com",
    password: "shahRukhKhan123",
    userHandler: "shahRukhKhan123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Aishwarya",
    lastName: "Rai",
    username: "aishwaryarai@gmail.com",
    password: "aishwaryaRai123",
    userHandler: "aishwaryaRai123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Priyanka",
    lastName: "Chopra",
    username: "priyankachopra@gmail.com",
    password: "priyankaChopra123",
    userHandler: "priyankaChopra123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Salman",
    lastName: "Khan",
    username: "salmanKhan@gmail.com",
    password: "salmanKhan123",
    userHandler: "salmanKhan123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Deepika",
    lastName: "Padukone",
    username: "deepikapadukone@gmail.com",
    password: "deepikaPadukone123",
    userHandler: "deepikaPadukone123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Ranveer",
    lastName: "Singh",
    username: "ranveersingh@gmail.com",
    password: "ranveerSingh123",
    userHandler: "ranveerSingh123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Kareena",
    lastName: "Kapoor",
    username: "kareenakapoor@gmail.com",
    password: "kareenaKapoor123",
    userHandler: "kareenaKapoor123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Hrithik",
    lastName: "Roshan",
    username: "hrithikroshan@gmail.com",
    password: "hrithikRoshan123",
    userHandler: "hrithikRoshan123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Alia",
    lastName: "Bhatt",
    username: "aliabhatt@gmail.com",
    password: "aliaBhatt123",
    userHandler: "aliaBhatt123",
    bookmarks: [],
    followers:[],
    following:[],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
